export const initData = [
  {
    address: "106 Kendell Street",
    billFromAddress: "19 Union Terrace",
    billFromCity: "London",
    billFromCountry: "United Kingdom",
    billFromPostCode: "E1 3EZ",
    city: "Sharrington",
    clientName: "Jensen Huang",
    country: "United Kingdom",
    date: new Date("2022-08-10T00:00:00.000Z"),
    email: "jensenh@mail.com",
    id: "aidb0wwB",
    isPaid: false,
    itemList: [
      {
        id: "jkisZMeE",
        itemName: "Brand Guidelines",
        qty: 1,
        price: 1800.9,
        total: 1800.9,
      },
    ],
    paymentTerm: "1",
    postCode: "NR24 5WQ",
    projectDescription: "Re-branding",
    totalAmt: 1800.9,
    "mantine-4ynm2slkz": "August 10, 2022",
  },
  {
    address: "84 Church Way",
    billFromAddress: "19 Union Terrace",
    billFromCity: "London",
    billFromCountry: "United Kingdom",
    billFromPostCode: "E1 3EZ",
    city: "Bradford",
    clientName: "Alex Grim",
    country: "United Kingdom",
    date: new Date("2023-07-22T00:00:00.000Z"),
    email: "alexgrim@mail.com",
    id: "A0PXAK7t",
    isPaid: true,
    itemList: [
      {
        id: "jkisZMeE",
        itemName: "Banner Design",
        qty: 1,
        price: 156,
        total: 156,
      },
      {
        id: "Kpgw8Jce",
        itemName: "Email Design",
        qty: 2,
        price: 200,
        total: 400,
      },
    ],
    paymentTerm: "21",
    postCode: "BD1 9PB",
    projectDescription: "Graphic Design",
    totalAmt: 556,
    "mantine-9m4clqi5k": "August 22, 2023",
  },
];
